CREATE TABLE IF NOT EXISTS tbl_users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    cpf VARCHAR(255) NOT NULL UNIQUE,
    password_reset_code VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tbl_products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    preco DOUBLE PRECISION NOT NULL,
    codigo_barras VARCHAR(255) NOT NULL UNIQUE,
    estoque INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS tbl_cart (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    is_finalizado BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_cart_user
        FOREIGN KEY (user_id) REFERENCES tbl_users(id)
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS tbl_pedidos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data TIMESTAMP,
    valor_total DOUBLE PRECISION NOT NULL,
    payment_intent_id VARCHAR(255),
    user_id INTEGER,
    CONSTRAINT fk_pedido_user
        FOREIGN KEY (user_id) REFERENCES tbl_users(id)
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS tbl_cart_item (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    pedido_id INTEGER,
    quantity INTEGER NOT NULL,
    CONSTRAINT fk_cart_item_cart
        FOREIGN KEY (cart_id) REFERENCES tbl_cart(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_cart_item_product
        FOREIGN KEY (product_id) REFERENCES tbl_products(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_cart_item_pedido
        FOREIGN KEY (pedido_id) REFERENCES tbl_pedidos(id)
        ON DELETE SET NULL
);

-- Tabela legada de pagamentos (útil se você ainda usar esse registro fora do JPA)
CREATE TABLE IF NOT EXISTS tbl_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id INTEGER,
    user_id INTEGER,
    stripe_payment_id VARCHAR(255),
    status VARCHAR(30),
    description VARCHAR(255),
    currency VARCHAR(10),
    created_at TIMESTAMP,
    CONSTRAINT fk_payment_cart
        FOREIGN KEY (cart_id) REFERENCES tbl_cart(id)
        ON DELETE SET NULL,
    CONSTRAINT fk_payment_user
        FOREIGN KEY (user_id) REFERENCES tbl_users(id)
        ON DELETE SET NULL,
    CONSTRAINT chk_payment_status
        CHECK (status IN ('CANCELLED', 'PENDING', 'SUCCEEDED', 'FAILED') OR status IS NULL)
);

CREATE INDEX IF NOT EXISTS idx_cart_user_id ON tbl_cart(user_id);
CREATE INDEX IF NOT EXISTS idx_cart_item_cart_id ON tbl_cart_item(cart_id);
CREATE INDEX IF NOT EXISTS idx_cart_item_product_id ON tbl_cart_item(product_id);
CREATE INDEX IF NOT EXISTS idx_cart_item_pedido_id ON tbl_cart_item(pedido_id);
CREATE INDEX IF NOT EXISTS idx_pedido_user_id ON tbl_pedidos(user_id);
CREATE INDEX IF NOT EXISTS idx_payment_user_id ON tbl_payments(user_id);