CREATE DATABASE db_mercado;

USE db_mercado;

CREATE TABLE IF NOT EXISTS tbl_users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    cpf VARCHAR(255) NOT NULL UNIQUE,
    password_reset_code VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);